version: '3.1'
services:
  self-signed-https:
    image: nwtgck/self-signed-https:v0.1.0
    ports:
      - '8080:80'
      - '4443:443'
    depends_on:
      - ghost
    restart: always
    environment:
      TARGET_HOST: ghost
      TARGET_PORT: 2368

  ghost:
    image: ghost
    restart: always
    expose:
      - "2368"
